// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzhnjauddilznxkrlzjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6aG5qYXVkZGlsem54a3Jsemp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjE5ODUsImV4cCI6MjA2ODczNzk4NX0.lVVBNoUtH6n7sCleu0_AN9EuP_MWCIRNeLsljKivljg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});